version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha

    working_directory: ~/ziggy

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            ./gradlew resolveConfigurations --parallel --console=plain
            echo ${ZIGGY_KEYSTORE} | base64 --decode > ${HOME}/release-key.jks  # APK signing key is in this keystore

      - run:
          name: Build artifacts and run tests
          command: |
            sdkmanager  "system-images;android-25;google_apis;armeabi-v7a"
            echo "no" | avdmanager create avd -n test -d pixel -k  "system-images;android-25;google_apis;armeabi-v7a"
            emulator -avd test -noaudio -no-window -gpu swiftshader -verbose -qemu &
            # export ADB_INSTALL_TIMEOUT=120
            # pushd /usr/local/android-sdk/emulator
            # ./emulator -avd test -noaudio -no-window -gpu swiftshader -verbose -qemu &
            # popd
            # adb wait-for-device
            # adb start-server
            # A=$(adb shell getprop sys.boot_completed | tr -d '\r')

            # while [ "$A" != "1" ]; do
            #     sleep 2
            #     A=$(adb shell getprop sys.boot_completed | tr -d '\r')
            #     echo "Waiting for emulator to finish booting..."
            # done
            # adb devices
            # adb logcat &
            #./gradlew build --console=plain
            circle-android wait-for-device
            ./gradlew connectedInternalDebugAndroidTest --debug --console=plain
            ./gradlew check assembleInternalRelease --info --console=plain 
      - run:
          name: Collect test results
          command: |
            mkdir -p /test-results
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} /test-results/ \;
      - store_test_results:
          path: /test-results/