version: 2

jobs:
  build:
    docker:
      - image: quartic/uber-builder:47

    working_directory: ~/ziggy

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            env
            ./gradlew resolveConfigurations --parallel --console=plain

      - run:
          name: Build artifacts and run tests
          command: |
            export ADB_INSTALL_TIMEOUT=120
            pushd /usr/local/android-sdk/emulator
            ./emulator -memory 512 -avd test -noaudio -no-window -gpu swiftshader -verbose &
            popd
            adb wait-for-device
            A=$(adb shell getprop sys.boot_completed | tr -d '\r')

            while [ "$A" != "1" ]; do
                sleep 2
                A=$(adb shell getprop sys.boot_completed | tr -d '\r')
                echo "Waiting for emulator to finish booting..."
            done

            ./gradlew connectedInternalDebugAndroidTest --debug --console=plain
            ./gradlew check assembleInternalRelease --info --console=plain 
