internal:
  backendBaseUrl: http://10.0.2.2:9000/api/
  enableLiveUpload: true
  liveUploadIntervalMilliseconds: 5000
  enablePeriodicUpload: true
  periodicUploadIntervalMilliseconds: 3600
real:
  backendBaseUrl: https://diggers.dev.quartic.io/api/
  enableLiveUpload: true
  liveUploadIntervalMilliseconds: 5000
  enablePeriodicUpload: true
  periodicUploadIntervalMilliseconds: 3600
